/*
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openai

import (
	"encoding/json"
)

// checks if the MessageObjectAttachmentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageObjectAttachmentsInner{}

// MessageObjectAttachmentsInner struct for MessageObjectAttachmentsInner
type MessageObjectAttachmentsInner struct {
	// The ID of the file to attach to the message.
	FileId *string `json:"file_id,omitempty"`
	// The tools to add this file to.
	Tools []MessageObjectAttachmentsInnerToolsInner `json:"tools,omitempty"`
}

// NewMessageObjectAttachmentsInner instantiates a new MessageObjectAttachmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageObjectAttachmentsInner() *MessageObjectAttachmentsInner {
	this := MessageObjectAttachmentsInner{}
	return &this
}

// NewMessageObjectAttachmentsInnerWithDefaults instantiates a new MessageObjectAttachmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageObjectAttachmentsInnerWithDefaults() *MessageObjectAttachmentsInner {
	this := MessageObjectAttachmentsInner{}
	return &this
}

// GetFileId returns the FileId field value if set, zero value otherwise.
func (o *MessageObjectAttachmentsInner) GetFileId() string {
	if o == nil || IsNil(o.FileId) {
		var ret string
		return ret
	}
	return *o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageObjectAttachmentsInner) GetFileIdOk() (*string, bool) {
	if o == nil || IsNil(o.FileId) {
		return nil, false
	}
	return o.FileId, true
}

// HasFileId returns a boolean if a field has been set.
func (o *MessageObjectAttachmentsInner) HasFileId() bool {
	if o != nil && !IsNil(o.FileId) {
		return true
	}

	return false
}

// SetFileId gets a reference to the given string and assigns it to the FileId field.
func (o *MessageObjectAttachmentsInner) SetFileId(v string) {
	o.FileId = &v
}

// GetTools returns the Tools field value if set, zero value otherwise.
func (o *MessageObjectAttachmentsInner) GetTools() []MessageObjectAttachmentsInnerToolsInner {
	if o == nil || IsNil(o.Tools) {
		var ret []MessageObjectAttachmentsInnerToolsInner
		return ret
	}
	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageObjectAttachmentsInner) GetToolsOk() ([]MessageObjectAttachmentsInnerToolsInner, bool) {
	if o == nil || IsNil(o.Tools) {
		return nil, false
	}
	return o.Tools, true
}

// HasTools returns a boolean if a field has been set.
func (o *MessageObjectAttachmentsInner) HasTools() bool {
	if o != nil && !IsNil(o.Tools) {
		return true
	}

	return false
}

// SetTools gets a reference to the given []MessageObjectAttachmentsInnerToolsInner and assigns it to the Tools field.
func (o *MessageObjectAttachmentsInner) SetTools(v []MessageObjectAttachmentsInnerToolsInner) {
	o.Tools = v
}

func (o MessageObjectAttachmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageObjectAttachmentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FileId) {
		toSerialize["file_id"] = o.FileId
	}
	if !IsNil(o.Tools) {
		toSerialize["tools"] = o.Tools
	}
	return toSerialize, nil
}

type NullableMessageObjectAttachmentsInner struct {
	value *MessageObjectAttachmentsInner
	isSet bool
}

func (v NullableMessageObjectAttachmentsInner) Get() *MessageObjectAttachmentsInner {
	return v.value
}

func (v *NullableMessageObjectAttachmentsInner) Set(val *MessageObjectAttachmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageObjectAttachmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageObjectAttachmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageObjectAttachmentsInner(val *MessageObjectAttachmentsInner) *NullableMessageObjectAttachmentsInner {
	return &NullableMessageObjectAttachmentsInner{value: val, isSet: true}
}

func (v NullableMessageObjectAttachmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageObjectAttachmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


