/*
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

API version: 2.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openai

import (
	"encoding/json"
	"fmt"
)

// MessageObjectAttachmentsInnerToolsInner - struct for MessageObjectAttachmentsInnerToolsInner
type MessageObjectAttachmentsInnerToolsInner struct {
	AssistantToolsCode *AssistantToolsCode
	AssistantToolsFileSearchTypeOnly *AssistantToolsFileSearchTypeOnly
}

// AssistantToolsCodeAsMessageObjectAttachmentsInnerToolsInner is a convenience function that returns AssistantToolsCode wrapped in MessageObjectAttachmentsInnerToolsInner
func AssistantToolsCodeAsMessageObjectAttachmentsInnerToolsInner(v *AssistantToolsCode) MessageObjectAttachmentsInnerToolsInner {
	return MessageObjectAttachmentsInnerToolsInner{
		AssistantToolsCode: v,
	}
}

// AssistantToolsFileSearchTypeOnlyAsMessageObjectAttachmentsInnerToolsInner is a convenience function that returns AssistantToolsFileSearchTypeOnly wrapped in MessageObjectAttachmentsInnerToolsInner
func AssistantToolsFileSearchTypeOnlyAsMessageObjectAttachmentsInnerToolsInner(v *AssistantToolsFileSearchTypeOnly) MessageObjectAttachmentsInnerToolsInner {
	return MessageObjectAttachmentsInnerToolsInner{
		AssistantToolsFileSearchTypeOnly: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *MessageObjectAttachmentsInnerToolsInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AssistantToolsCode
	err = newStrictDecoder(data).Decode(&dst.AssistantToolsCode)
	if err == nil {
		jsonAssistantToolsCode, _ := json.Marshal(dst.AssistantToolsCode)
		if string(jsonAssistantToolsCode) == "{}" { // empty struct
			dst.AssistantToolsCode = nil
		} else {
			match++
		}
	} else {
		dst.AssistantToolsCode = nil
	}

	// try to unmarshal data into AssistantToolsFileSearchTypeOnly
	err = newStrictDecoder(data).Decode(&dst.AssistantToolsFileSearchTypeOnly)
	if err == nil {
		jsonAssistantToolsFileSearchTypeOnly, _ := json.Marshal(dst.AssistantToolsFileSearchTypeOnly)
		if string(jsonAssistantToolsFileSearchTypeOnly) == "{}" { // empty struct
			dst.AssistantToolsFileSearchTypeOnly = nil
		} else {
			match++
		}
	} else {
		dst.AssistantToolsFileSearchTypeOnly = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AssistantToolsCode = nil
		dst.AssistantToolsFileSearchTypeOnly = nil

		return fmt.Errorf("data matches more than one schema in oneOf(MessageObjectAttachmentsInnerToolsInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(MessageObjectAttachmentsInnerToolsInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MessageObjectAttachmentsInnerToolsInner) MarshalJSON() ([]byte, error) {
	if src.AssistantToolsCode != nil {
		return json.Marshal(&src.AssistantToolsCode)
	}

	if src.AssistantToolsFileSearchTypeOnly != nil {
		return json.Marshal(&src.AssistantToolsFileSearchTypeOnly)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *MessageObjectAttachmentsInnerToolsInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AssistantToolsCode != nil {
		return obj.AssistantToolsCode
	}

	if obj.AssistantToolsFileSearchTypeOnly != nil {
		return obj.AssistantToolsFileSearchTypeOnly
	}

	// all schemas are nil
	return nil
}

type NullableMessageObjectAttachmentsInnerToolsInner struct {
	value *MessageObjectAttachmentsInnerToolsInner
	isSet bool
}

func (v NullableMessageObjectAttachmentsInnerToolsInner) Get() *MessageObjectAttachmentsInnerToolsInner {
	return v.value
}

func (v *NullableMessageObjectAttachmentsInnerToolsInner) Set(val *MessageObjectAttachmentsInnerToolsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageObjectAttachmentsInnerToolsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageObjectAttachmentsInnerToolsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageObjectAttachmentsInnerToolsInner(val *MessageObjectAttachmentsInnerToolsInner) *NullableMessageObjectAttachmentsInnerToolsInner {
	return &NullableMessageObjectAttachmentsInnerToolsInner{value: val, isSet: true}
}

func (v NullableMessageObjectAttachmentsInnerToolsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageObjectAttachmentsInnerToolsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


